// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using EntityFrameworkCoreBulkInsertsApp.Models;
using Microsoft.EntityFrameworkCore;

using static ConfigurationLibrary.Classes.ConfigurationHelper;

namespace EntityFrameworkCoreBulkInsertsApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customer { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConnectionString());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        modelBuilder
            .Entity<Customer>()
            .Property(e => e.Gender)
            .HasConversion(v => 
                v.ToString(), v => (Gender)Enum.Parse(typeof(Gender), v));

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}